name: Linux test build

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]



    steps:
    - name: Get Dependencies
      run: sudo apt-get install libasound2-dev libpulse-dev libgtk-3-dev

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Get CMake
      uses: lukka/get-cmake@latest
  
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with: 
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Run CMake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'ninja-multi-vcpkg'
        buildPreset: 'ninja-vcpkg-release'

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nesprime-${{ matrix.os }}
        path: builds/ninja-multi-vcpkg/Release/*
        retention-days: 1

  release:
    name: Draft Release  
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
  
      - name: Display Fetched Artifacts
        run: ls -R artifacts

      - name: Compress Artifacts
        run: |
          cd artifacts
          for folder in */; do
            base=$(basename "$folder")
            zip -r "${base}.zip" "$folder"
          done

      - name: Create Draft Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "test"
          prerelease: true
          title: "Test Build"
          files: |
            artifacts/*.zip


      
    